####### Admin Signup

POST http://localhost:8080/admin/signup
Content-Type: application/json

{
    "name":"Uzair Naseer",
    "password":"admin",
    "email":"Uzair001@gmail.com"

}

############# Admin login
POST http://localhost:8080/admin/login
Content-Type: application/json

{
"email":"admin001@gmail.com",
"password":"admin"
}

#################### ADMIN ==> get Profile
GET http://localhost:8080/admin/profile


############# Admin Search Doctor
GET http://localhost:8080/admin/doctor/search/hheello

############# Admin Search Patient
GET http://localhost:8080/admin/patient/search/Waqassaleem3@gmail.com

####### Doctor SignUp


POST http://localhost:8080/admin/doctor/signup
Content-Type: application/json

{
    "name":"Dr.Hasnainn",
    "password":"docaczxcsr7863",
    "email":"dqwecxzda9301@gmail.com",
     "specialization":"Nephrologist",
    "medicalLicenseNo":"723SJQ",
    "gender":"Male",
    "phoneNumber":"012872621431"

}


############# Doctor login
POST http://localhost:8080/admin/doctor/login
Content-Type: application/json

{
"email":"Abdullah372@gmail.com"
}

##################### update doctor
PATCH http://localhost:8080/admin/doctor/update
Content-Type: application/json

{
   "name":"Dr.Waqas",
    "password":"doctor7863",
    "email":"Abdullah372@gmail.com",
    "specialization":"Nephrologist",
    "medicalLicenseNo":"723SJQ",
    "gender":"Male",
    "phoneNumber":"012872621431",
    "adminID":"6463e56b2621ab5034d067d8"

}


#################### ADMIN ==> get All Doctor
GET http://localhost:8080/admin/getAllDoctor/6463e56b2621ab5034d067d8

##################### delete doctor
DELETE  http://localhost:8080/admin/doctor/delete/umair521@gmail.com

####### Patient SignUp

POST http://localhost:8080/admin/patient/signup
Content-Type: application/json

{
    "name":"Ibara Hussain",
    "password":"87236",
    "email":"Iewwdw76@gmail.com",
    "medical_history":"Allergic to penicillin",
    "phoneNumber":"0313648866",
    "gender":"Male",
    "doctorID":"6469edca6e385ff5f0700b5d"

}

############# Patient login
POST http://localhost:8080/admin/Patient/login
Content-Type: application/json

{
"email":"Awais21@gmail.com"
}



#################### ADMIN ==> get All Patient
GET http://localhost:8080/admin/getAllPatient/6463e56b2621ab5034d067d8

##################### delete doctor
DELETE  http://localhost:8080/admin/patient/delete/AzizNaseer231@gmail.com


#################### View All complaints
GET http://localhost:8080/admin/getAllComplaints


############# Cookies Request
POST http://localhost:8080
Content-Type: application/json

{
"name":"admin",
"password":"SE7"
}


############# Admin create session
POST http://localhost:8080/admin/createSession
Content-Type: application/json

{
"name":"admin",
"password":"SE7"

}