############# Doctor login
POST http://localhost:8080/doctor/login
Content-Type: application/json

{
"email":"uzairiqbal3313@gmail.com",
"password":"331371"
}

############# Doctor Update Schedule
PUT http://localhost:8080/doctor/updateSchedule
Content-Type: application/json

{
"email":"newd123@gmail.com",
"selectedSlots":["1:00 - 1:30 PM"]
}


############# Doctor profile
GET http://localhost:8080/doctor/profile/newd123@gmail.com



#################### DOCTOR ==> get All Patient
GET http://localhost:8080/doctor/getAllPatients/643de1dc1574ede74f6ec540
