############# Doctor login
POST http://localhost:8080/doctor/login
Content-Type: application/json

{
"email":"uzairiqbal3313@gmail.com",
"password":"331371"
}

############# Doctor Update Schedule
PUT http://localhost:8080/doctor/updateSchedule
Content-Type: application/json

{
"email":"newd123@gmail.com",
"selectedSlots":["1:00 - 1:30 PM","9:00 - 1:30 AM","9:30 - 10:00 AM","11:00 - 11:30 AM"]
}

############# Doctor Get Appiontments
GET http://localhost:8080/doctor/appiontments/newd123@gmail.com


############# Doctor profile
GET http://localhost:8080/doctor/profile/newd123@gmail.com

############# Doctor's Prescription
POST http://localhost:8080/doctor/createPrescription
Content-Type: application/json

{
"doctorEmail":"newd123@gmail.com",
"patientEmail":"UzairAziz4893@gmail.com",
"description":"Some prescription description ",
"dosage":"2-1-3",
"medicineName":"Panadol",
"startDate":"Tue Aug 15 2023 00:00:00 GMT+0500 ",
"endDate":"Thu Aug 17 2023 00:00:00 GMT+0500 "
}

#################### DOCTOR ==> get All Patient
GET http://localhost:8080/doctor/getAllPatients/643de1dc1574ede74f6ec540


#################### Patient ==> get  PDF Reports
GET http://localhost:8080/doctor/getreports/newd123@gmail.com