####### Patient SignUp

POST http://localhost:8080/patient/signup
Content-Type: application/json

{
     "name":"ALI  Hussan",
    "password":"87236",
    "email":"Alihassan23@gmail.com",
    "medical_history":"Allergic to penicillin",
    "phoneNumber":"0313648866",
    "gender":"Male"

}


############# Patient login
POST http://localhost:8080/patient/login
Content-Type: application/json

{
"email":"UzairAziz4893@gmail.com",
"password":"Mypass"
}

############# Create Appointment
POST http://localhost:8080/patient/createAppointment
Content-Type: application/json

{
"name":" Uzair",
"email":"UzairAziz4893@gmail.com",
"doctorEmail":"railsa3313@gmail.com",
"slot":"1:30 - 2:00 PM",
"createdAt": "2023-09-30"
}


####### Make Appointment

POST http://localhost:8080/patient/makeAppointment
Content-Type: application/json

{
    "type":"Physical",
    "status":"pending",
    "doctorID":"6465539dc81287f0c274a0ad"

}

#################### Patient ==> get All Pending Appointments
GET http://localhost:8080/patient/getAllPendingApp/6465539dc81287f0c274a0ad


#######  Make Complaint

POST http://localhost:8080/patient/submitComplaint
Content-Type: application/json

{
    "email":"UzairNaseer123@gmail.com",
    "description":"website 66 performance is very low frontend",
    "compainner":"Patient"

}
